// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: raft.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RaftRpcServiceClient is the client API for RaftRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftRpcServiceClient interface {
	RequestVote(ctx context.Context, in *RequestVoteArgs, opts ...grpc.CallOption) (*RequestVoteReply, error)
}

type raftRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftRpcServiceClient(cc grpc.ClientConnInterface) RaftRpcServiceClient {
	return &raftRpcServiceClient{cc}
}

func (c *raftRpcServiceClient) RequestVote(ctx context.Context, in *RequestVoteArgs, opts ...grpc.CallOption) (*RequestVoteReply, error) {
	out := new(RequestVoteReply)
	err := c.cc.Invoke(ctx, "/RaftRpcService/RequestVote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftRpcServiceServer is the server API for RaftRpcService service.
// All implementations must embed UnimplementedRaftRpcServiceServer
// for forward compatibility
type RaftRpcServiceServer interface {
	RequestVote(context.Context, *RequestVoteArgs) (*RequestVoteReply, error)
	mustEmbedUnimplementedRaftRpcServiceServer()
}

// UnimplementedRaftRpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRaftRpcServiceServer struct {
}

func (UnimplementedRaftRpcServiceServer) RequestVote(context.Context, *RequestVoteArgs) (*RequestVoteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedRaftRpcServiceServer) mustEmbedUnimplementedRaftRpcServiceServer() {}

// UnsafeRaftRpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftRpcServiceServer will
// result in compilation errors.
type UnsafeRaftRpcServiceServer interface {
	mustEmbedUnimplementedRaftRpcServiceServer()
}

func RegisterRaftRpcServiceServer(s grpc.ServiceRegistrar, srv RaftRpcServiceServer) {
	s.RegisterService(&RaftRpcService_ServiceDesc, srv)
}

func _RaftRpcService_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftRpcServiceServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RaftRpcService/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftRpcServiceServer).RequestVote(ctx, req.(*RequestVoteArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftRpcService_ServiceDesc is the grpc.ServiceDesc for RaftRpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftRpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RaftRpcService",
	HandlerType: (*RaftRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _RaftRpcService_RequestVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}
